Feature/admin reviews
peaksoft-school/Gadgetarium-js14 pull request #32
Opened 2024-11-01 12:53 UTC by kubanchbekov

2024-11-01 14:14 UTC, kursanbekova commented
const StyledRow = styled("div")({
  display: "flex",
  alignItems: "center",
  padding: "15px 20px",
  borderBottom: "1px solid black",
  width: "100%",
  boxSizing: "border-box",
});    

<StyledRow
      style={{
        display: "grid",
        alignItems: "start",
        gap: "10px",
        gridTemplateColumns: "0.1fr 0.20fr 0.46fr 1.5fr 0.2fr ",
      }}
    >  Дай стили через styled, либо inline-стили,
    Убери один из вариантов

2024-11-06 14:05 UTC, AziatAbd requested changes

2024-11-06 14:05 UTC, AziatAbd commented on src/components/UI/admin/AdminReview.jsx
> +        )}
из бэка вам придет только один comment.

2024-11-06 14:05 UTC, AziatAbd commented on src/components/UI/admin/AdminReview.jsx
> +      ))}
нужна проверка на массив, если пустой массив то должно выйти какой-нибудь текст

2024-11-08 09:10 UTC, merged